name: miscelaneos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.0
  flutter_riverpod: ^2.3.6
  geolocator: ^12.0.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.6.1
  local_auth: ^2.2.0
  permission_handler: ^10.2.0
  sensors_plus: ^5.0.1
  share_plus: ^9.0.0
  uuid: ^4.4.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
